In [4]:
import pandas as pd
import numpy as np

import viz

%matplotlib inline



In [83]:
np.random.seed(20)

throws = np.array([1,2,3,4,5,6])

n_rolls = 50 # number of rolls
n_rows = 2  # a pair of rolls

###  1. How likely is it that you roll doubles when rolling two dice?

In [85]:

rolls = np.random.choice(throws, n_rolls * n_rows).reshape(n_rolls, n_rows)
rolls
# numpy syntax(numbers being randomly selected, # of spins) # reshaped to fit into list


array([[4, 3],
       [5, 3],
       [2, 5],
       [4, 3],
       [1, 1],
       [6, 3],
       [3, 4],
       [4, 1],
       [6, 1],
       [2, 6],
       [6, 3],
       [3, 6],
       [4, 3],
       [2, 4],
       [3, 4],
       [6, 6],
       [4, 2],
       [1, 3],
       [4, 4],
       [3, 4],
       [6, 6],
       [2, 1],
       [4, 1],
       [3, 3],
       [4, 4],
       [6, 6],
       [1, 3],
       [6, 2],
       [3, 4],
       [3, 2],
       [5, 5],
       [4, 4],
       [1, 3],
       [3, 4],
       [3, 3],
       [2, 6],
       [3, 2],
       [1, 3],
       [3, 5],
       [5, 4],
       [5, 1],
       [1, 4],
       [5, 1],
       [6, 6],
       [3, 2],
       [5, 5],
       [5, 1],
       [5, 2],
       [2, 4],
       [3, 2]])

In [99]:
df_rolls = pd.DataFrame(rolls)
df_rolls

0  1
0   4  3
1   5  3
2   2  5
3   4  3
4   1  1
5   6  3
6   3  4
7   4  1
8   6  1
9   2  6
10  6  3
11  3  6
12  4  3
13  2  4
14  3  4
15  6  6
16  4  2
17  1  3
18  4  4
19  3  4
20  6  6
21  2  1
22  4  1
23  3  3
24  4  4
25  6  6
26  1  3
27  6  2
28  3  4
29  3  2
30  5  5
31  4  4
32  1  3
33  3  4
34  3  3
35  2  6
36  3  2
37  1  3
38  3  5
39  5  4
40  5  1
41  1  4
42  5  1
43  6  6
44  3  2
45  5  5
46  5  1
47  5  2
48  2  4
49  3  2

In [97]:
 
doubles = df_rolls.apply(lambda row: row[0] == row[1], axis = 1).sum()
doubles

12

In [98]:
chance_double = doubles / n_rolls
chance_double


0.24

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of  getting    more than three heads?

In [100]:
# 

flipped = np.array([0,1]) # heads = 1, tails = 0

n_flips = 1000
n_cols = 8

flip_trial = np.random.choice(flipped, n_flips * n_cols).reshape(n_flips, n_cols)
flip_trial


array([[1, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 1, 0, 0]])

In [102]:
df_flip_trial = pd.DataFrame(flip_trial)
df_flip_trial

0  1  2  3  4  5  6  7
0    1  0  1  0  1  0  0  0
1    1  1  0  1  0  0  0  0
2    1  0  1  0  1  1  1  1
3    1  0  1  0  1  1  1  0
4    1  1  0  1  0  0  1  0
..  .. .. .. .. .. .. .. ..
995  0  1  1  1  0  1  1  0
996  1  1  1  0  0  0  1  1
997  1  1  1  0  1  0  1  1
998  0  0  0  1  0  0  0  1
999  1  1  1  1  0  1  0  0

[1000 rows x 8 columns]

#### Exactly three heads

In [125]:
# Getting exactly 3 heads

triple_heads = np.sum(df_flip_trial, axis=1) == 3

triple_heads # Got it to be boolean, now i can add them up with sum()



0       True
1       True
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [126]:
triple_heads.head().sum()  
# Testing first five rows to see if it adds correctly. Looks like it, 2xTrue and 3xFalse. 

2

In [122]:
# used np.sum() function to add the 1's in the row. To do this, must use axis=1, otherwise it will add the column.
P_triple_heads = triple_heads.sum() / n_flips
P_triple_heads

216

#### More than three heads

In [127]:
# same code as above, just switched to 'more than' sign
three_plus_heads = np.sum(df_flip_trial, axis=1) > 3
three_plus_heads


0      False
1      False
2       True
3       True
4       True
       ...  
995     True
996     True
997     True
998    False
999     True
Length: 1000, dtype: bool

In [128]:
P_three_plus_heads = three_plus_heads.sum() / n_flips
P_three_plus_heads

0.64

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the  two billboards I drive past both have data science students on them?

In [134]:
web_dev = 1
ds = 2

draws = 1000
c_rows = 1

billboard = np.random.choice([web_dev, web_dev, web_dev, ds], draws * c_rows).reshape(draws, c_rows)
billboard


array([[1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [1],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [1],
       [1],
    

In [135]:
df_billboard = pd.DataFrame(billboard) #turned into df to further manipulate/filter data
df_billboard

0
0    1
1    1
2    1
3    2
4    2
..  ..
995  1
996  1
997  2
998  1
999  1

[1000 rows x 1 columns]

In [136]:
ds_selected = np.sum(df_billboard, axis=1) == 2 
# used sum function to see if row is equal to 2 for ds
ds_selected

0      False
1      False
2      False
3       True
4       True
       ...  
995    False
996    False
997     True
998    False
999    False
Length: 1000, dtype: bool

In [141]:
ds_selected.sum() # count number of true rows

248

#### Percentage for 1 billboard

In [139]:
P_ds = ds_selected.sum() / draws # divided count of true rows by number of draws for percentage for
P_ds

0.248

#### Percentage for 2 billboards in a row

In [144]:
P_two_ds = P_ds * P_ds # multiply probability by itself to find probability to be on a second billboard
P_two_ds

0.061503999999999996

###  4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from   the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? 
### (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

### # 5. Compare Heights
#### 5a. Men have an average height of 178 cm and standard deviation of 8cm.

#### 5b. Women have a mean of 170, sd = 6cm.


#### 5c. Since you have means and standard deviations, you can use np.random.normal to generate observations.


#### 5d. If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?


### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?


#### 6a. What is the probability that we observe an installation issue within the first 150 students that download anaconda?


#### 6b. How likely is it that 450 students all download anaconda without an issue?


### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park.However, you haven't seen a food truck there in 3 days. How unlikely is this?


#### 7b. How likely is it that a food truck will show up sometime this week?


### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

